# Generated by Django 4.0.6 on 2022-08-01 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmaciaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
    ]
