# Generated by Django 4.0.6 on 2022-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaciaApp', '0002_remove_bill_amount_remove_bill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='medicamentos', max_length=100, verbose_name='Category'),
        ),
    ]
