# Generated by Django 4.0.6 on 2022-08-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmaciaApp', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
        migrations.CreateModel(
            name='OrdenDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=100, verbose_name='Price')),
                ('amount', models.IntegerField(max_length=100, verbose_name='Amount')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenDetail', to='farmaciaApp.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenDetail', to='farmaciaApp.product')),
            ],
        ),
    ]
