# Generated by Django 4.0.6 on 2022-08-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmaciaApp', '0004_remove_bill_products_ordendetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendetail',
            old_name='orden',
            new_name='bill',
        ),
    ]
